import "../index.css";
const defaultSettings = {
  WAITING_TEXT: {
    xsm: {
      FONT_SIZE: 19,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.45,
      CANVAS_POSITION_Y: 0.55,
    },
    sm: {
      FONT_SIZE: 16,
      LETTER_SPACING: 1,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    md: {
      FONT_SIZE: 18,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    lmd: {
      FONT_SIZE: 22,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    lg: {
      FONT_SIZE: 30,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    xl: {
      FONT_SIZE: 30,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    xl1300: {
      FONT_SIZE: 30,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    xxl: {
      FONT_SIZE: 30,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.55,
    },
    FONT_FAMILY: "Poppins",
    TEXT_SCALE_X: 1.2,
    TEXT_SCALE_y: 1.2,
  },
  MULTIPLIER_TEXT: {
    xsm: {
      FONT_SIZE: 68,
      CANVAS_POSITION_X: 0.45,
      CANVAS_POSITION_Y: 0.5,
    },
    sm: {
      FONT_SIZE: 68,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    md: {
      FONT_SIZE: 78,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    lmd: {
      FONT_SIZE: 78,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    lg: {
      FONT_SIZE: 100,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    xl: {
      FONT_SIZE: 100,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    xl1300: {
      FONT_SIZE: 100,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    xxl: {
      FONT_SIZE: 100,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.5,
    },
    FONT_FAMILY: "Arial",
    FONT_WEIGHT: "bold",
  },
  PROP: {
    xsm: {
      SCALE_SIZE: 0.4,
      CANVAS_POSITION_X: 0.45,
      CANVAS_POSITION_Y: 0.32,
    },
    sm: {
      SCALE_SIZE: 0.4,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    md: {
      SCALE_SIZE: 0.45,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    lmd: {
      SCALE_SIZE: 0.6,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    lg: {
      SCALE_SIZE: 0.9,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    xl: {
      SCALE_SIZE: 0.9,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    xl1300: {
      SCALE_SIZE: 0.9,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    xxl: {
      SCALE_SIZE: 0.9,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.33,
    },
    ROTATING_SPEED: 0.07,
  },
  FLEW_AWAY_TEXT: {
    xsm: {
      FONT_SIZE: 20,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.45,
      CANVAS_POSITION_Y: 0.25,
    },
    sm: {
      FONT_SIZE: 20,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.25,
    },
    md: {
      FONT_SIZE: 26,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.3,
    },
    lmd: {
      FONT_SIZE: 26,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.3,
    },
    lg: {
      FONT_SIZE: 36,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.3,
    },
    xl: {
      FONT_SIZE: 36,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.3,
    },
    xl1300: {
      FONT_SIZE: 36,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.3,
    },
    xxl: {
      FONT_SIZE: 36,
      LETTER_SPACING: 0,
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.3,
    },

    FONT_FAMILY: "Poppins",
    TEXT_SCALE_X: 1,
    TEXT_SCALE_y: 1,
  },
  REDUCTING_PROGRESS_BAR: {
    xsm: {
      CANVAS_POSITION_X: 0.44,
      CANVAS_POSITION_Y: 0.68,
      BAR_WIDTH: 0.29,
      BAR_HEIGHT: 0.02,
    },
    sm: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.7,
      BAR_WIDTH: 0.27,
      BAR_HEIGHT: 0.02,
    },
    md: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.68,
      BAR_WIDTH: 0.22,
      BAR_HEIGHT: 0.02,
    },
    lmd: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.64,
      BAR_WIDTH: 0.22,
      BAR_HEIGHT: 0.02,
    },
    lg: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.65,
      BAR_WIDTH: 0.26,
      BAR_HEIGHT: 0.02,
    },
    xl: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.65,
      BAR_WIDTH: 0.26,
      BAR_HEIGHT: 0.02,
    },
    xl1300: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.65,
      BAR_WIDTH: 0.26,
      BAR_HEIGHT: 0.02,
    },
    xxl: {
      CANVAS_POSITION_X: 0.5,
      CANVAS_POSITION_Y: 0.65,
      BAR_WIDTH: 0.26,
      BAR_HEIGHT: 0.02,
    },
    CANVAS_POSITION_X: 0.5,
    CANVAS_POSITION_Y: 0.7,
  },
  HORIZONTAL_LINE: {
    xsm: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.86,
    },
    sm: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.86,
    },
    md: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.86,
    },
    lmd: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.86,
    },
    lg: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.9,
    },
    xl: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.9,
    },
    xl1300: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.9,
    },
    xxl: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 1,
      LINE_END_POINT_Y: 0.9,
    },
    LINE_COLOR: 0x403134,
  },
  HORIZONTAL_DOTTED_LINE: {
    xsm: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
    sm: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
    md: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
    lmd: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },

    lg: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
    xl: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
    xl1300: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
    xxl: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.1,
      DOT_OFFSET_Y: 0.94,
      OFFSET_BETWEEN_DOTS: 1,
    },
  },
  VERTICAL_LINE: {
    xsm: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 0.08,
      LINE_END_POINT_Y: 0,
    },
    sm: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 0.08,
      LINE_END_POINT_Y: 0,
    },
    md: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 0.08,
      LINE_END_POINT_Y: 0,
    },
    lmd: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.08,
      LINE_START_POINT_Y: 0.86,
      LINE_END_POINT_X: 0.08,
      LINE_END_POINT_Y: 0,
    },
    lg: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 0.05,
      LINE_END_POINT_Y: 0,
    },
    xl: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 0.05,
      LINE_END_POINT_Y: 0,
    },
    xl1300: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 0.05,
      LINE_END_POINT_Y: 0,
    },
    xxl: {
      LINE_WIDTH: 1,
      LINE_START_POINT_X: 0.05,
      LINE_START_POINT_Y: 0.9,
      LINE_END_POINT_X: 0.05,
      LINE_END_POINT_Y: 0,
    },
    LINE_COLOR: 0x403134,
  },
  VERTICAL_DOTTED_LINE: {
    xsm: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.03,
      DOT_OFFSET_Y: 0.83,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    sm: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.03,
      DOT_OFFSET_Y: 0.83,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    md: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.03,
      DOT_OFFSET_Y: 0.85,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    lmd: {
      DOT_SCALE: 0.2,
      DOT_OFFSET_X: 0.03,
      DOT_OFFSET_Y: 0.85,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    lg: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.02,
      DOT_OFFSET_Y: 0.84,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    xl: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.02,
      DOT_OFFSET_Y: 0.84,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    xl1300: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.02,
      DOT_OFFSET_Y: 0.84,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    xxl: {
      DOT_SCALE: 0.3,
      DOT_OFFSET_X: 0.02,
      DOT_OFFSET_Y: 0.84,
      OFFSET_BETWEEN_DOTS: 0.1,
    },
    TINT_COLOR: 0x117eb0,
  },
  QUAD_CURVE: {
    xsm: {
      CURVE_START_POINT_X: 0.08,
      CURVE_START_POINT_Y: 0.86,
      CURVE_END_POINT_X: 0.08,
      CURVE_END_POINT_Y: 0.86,
      CURVE_REACH_POINT_X: 0.55,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.75,
      GLIDE_POINT_Y: 0.65,
      AXIS_OFFSET: 0.08,
    },
    sm: {
      CURVE_START_POINT_X: 0.08,
      CURVE_START_POINT_Y: 0.86,
      CURVE_END_POINT_X: 0.08,
      CURVE_END_POINT_Y: 0.86,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.8,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.08,
    },
    md: {
      CURVE_START_POINT_X: 0.08,
      CURVE_START_POINT_Y: 0.86,
      CURVE_END_POINT_X: 0.08,
      CURVE_END_POINT_Y: 0.86,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.83,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.08,
    },
    lmd: {
      CURVE_START_POINT_X: 0.08,
      CURVE_START_POINT_Y: 0.86,
      CURVE_END_POINT_X: 0.08,
      CURVE_END_POINT_Y: 0.86,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.83,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.08,
    },
    lg: {
      CURVE_START_POINT_X: 0.05,
      CURVE_START_POINT_Y: 0.9,
      CURVE_END_POINT_X: 0.05,
      CURVE_END_POINT_Y: 0.9,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.7,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.054,
    },
    xl: {
      CURVE_START_POINT_X: 0.05,
      CURVE_START_POINT_Y: 0.9,
      CURVE_END_POINT_X: 1,
      CURVE_END_POINT_Y: 0.9,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.7,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.05,
    },
    xl1300: {
      CURVE_START_POINT_X: 0.05,
      CURVE_START_POINT_Y: 0.9,
      CURVE_END_POINT_X: 0.05,
      CURVE_END_POINT_Y: 0.9,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.7,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.058,
    },
    xxl: {
      CURVE_START_POINT_X: 0.05,
      CURVE_START_POINT_Y: 0.9,
      CURVE_END_POINT_X: 0.05,
      CURVE_END_POINT_Y: 0.9,
      CURVE_REACH_POINT_X: 0.65,
      CURVE_REACH_POINT_Y: 0.25,
      GLIDE_POINT_X: 0.7,
      GLIDE_POINT_Y: 0.45,
      AXIS_OFFSET: 0.058,
    },
  },
  PLANE: {
    xsm: {
      START_POINT_X: 0.08,
      START_POINT_Y: 0.86,
      PLANE_SCALE: 0.6,
    },
    sm: {
      START_POINT_X: 0.08,
      START_POINT_Y: 0.86,
      PLANE_SCALE: 0.6,
    },
    md: {
      START_POINT_X: 0.08,
      START_POINT_Y: 0.86,
      PLANE_SCALE: 0.65,
    },
    lmd: {
      START_POINT_X: 0.08,
      START_POINT_Y: 0.86,
      PLANE_SCALE: 0.65,
    },
    lg: {
      START_POINT_X: 0.05,
      START_POINT_Y: 0.9,
      PLANE_SCALE: 0.8,
    },
    xl: {
      START_POINT_X: 0.04,
      START_POINT_Y: 0.95,
      PLANE_SCALE: 1,
    },
    xl1300: {
      START_POINT_X: 0.05,
      START_POINT_Y: 0.9,
      PLANE_SCALE: 1,
    },
    xxl: {
      START_POINT_X: 0.05,
      START_POINT_Y: 0.9,
      PLANE_SCALE: 1,
    },
  },
};

export { defaultSettings };